/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SupportRole;

import model.EcoSys;
import model.Enterprise.Enterprise;
import model.Graph;
import model.Organization.Organization;
import model.Organization.OrgSupport;
import model.UserAccount.UserAccount;
import model.WorkQueue.SupportWorkRequest;
import model.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vidhi
 */
public class SupportWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSys model;
    private UserAccount userAccount;
    private OrgSupport orgSupport;
    Enterprise enterprise;
     Organization organization;
     HashMap<String,Integer> m;
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public SupportWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSys business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.model = business;
        this.orgSupport = (OrgSupport)organization;
        this.enterprise=enterprise;
        this.organization=organization;
        valueLabel.setText(enterprise.getName());
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : orgSupport.getWorkQueue().getWorkRequestList()){
            
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getSender();
              if(((SupportWorkRequest)request).getSupportreceiver()!=null){
                row[2] = ((SupportWorkRequest)request).getSupportreceiver();
            }else{
                row[2] = null;
            }
            row[3] = ((SupportWorkRequest)request).getSupportStatus();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        assignJButton = new javax.swing.JButton();
        processJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);
        if (workRequestJTable.getColumnModel().getColumnCount() > 0) {
            workRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(2).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 460, 110));

        assignJButton.setBackground(new java.awt.Color(0, 153, 153));
        assignJButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        assignJButton.setForeground(new java.awt.Color(255, 255, 255));
        assignJButton.setText("ASSIGN TO ME");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        processJButton.setBackground(new java.awt.Color(0, 153, 153));
        processJButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        processJButton.setForeground(new java.awt.Color(255, 255, 255));
        processJButton.setText("PROCESS");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        add(processJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 130, -1));

        refreshJButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        refreshJButton.setForeground(new java.awt.Color(0, 153, 153));
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        valueLabel.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!");
            return;
        }
        
          SupportWorkRequest request = (SupportWorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
        
        
        if(request.getSupportreceiver() == null){
            request.setSupportreceiver(userAccount);
            request.setStatus("Pending");
            populateTable();
            JOptionPane.showMessageDialog(null, "You are assigned as a dietician to this patient!!");
        }else if(request.getSupportreceiver() == userAccount) {
             JOptionPane.showMessageDialog(null, "you are already the dietician for this patient!!");
            return;
        }else if(request.getSupportreceiver()!=userAccount){
            JOptionPane.showMessageDialog(null, "Dieticain already assigned!!");
            return;
        }else{
             JOptionPane.showMessageDialog(null, "error allocating dietician!!");
            return;
        }
        populateTable();
        
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed
        
        int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!");
            return;
        }
        
        SupportWorkRequest request = (SupportWorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
     
        if(request.getSupportreceiver()==null){
             JOptionPane.showMessageDialog(null, "Assign a dietician first!!!!");
            return;
        }
        else if(request.getSupportreceiver() == userAccount){
            request.setStatus("Processing");
        
            ProcessWorkRequestJPanel processWorkRequestJPanel = new ProcessWorkRequestJPanel(userProcessContainer, request);
            userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }else if(request.getSupportreceiver()!=userAccount){
             JOptionPane.showMessageDialog(null, "You cant access this patient!!");
            return;
        }else{
            JOptionPane.showMessageDialog(null, "error in proceeding!");
            return;
        }
       
        
    }//GEN-LAST:event_processJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    
    
     public HashMap<String,Integer> createHashMap()
    {
        HashMap<String,Integer> map=new HashMap<String,Integer>();
        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            if(request.getType()!=null)
            {
           if(request.getType().equals("Patient")&& request.getReceiver()!= null ) 
 
               //&& request.getReceiver().equals(userAccount))
           {
                    ///based on granting status we can know- for ex how many are approved, rejected , pending
                     String key=((SupportWorkRequest)request).getSupportStatus();
                    if(request.getState()!=null)
                    {
                        map.put(key, map.containsKey(key)?map.get(key)+1:1);
                    }
            }
            //}
        }
        }
       return map; 
    }
    public void createPiechart(HashMap<String,Integer> m)
    {
        Graph g=new Graph();
       //ChartFrame c= 
               g.create(m);
        
//        JPanel imgPanel=new JPanel();
//            
//            
//            imgPanel.add(c);
//            imgPanel.setVisible(true);
//            add(imgPanel);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processJButton;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
