/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GranterRole;

import model.EcoSys;
import model.MailNew;
import model.Organization.OrgBillings;
import model.Organization.OrgGranting;
import model.Organization.Organization;
import model.UserAccount.UserAccount;
import model.WorkQueue.BillingWorkRequest;
import model.WorkQueue.GranterWorkRequest;
import userinterface.LabAssistantRole.*;
import model.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.AdministrativeRole.PatientInfoJPanel;
import userinterface.BillGeneratorRole.BillGeneratorWorkAreaJPanel;

/**
 *
 * @author Mitali
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    GranterWorkRequest request;
    EcoSys business;
    UserAccount account;
    String status;
    String amount;
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ProcessWorkRequestJPanel(JPanel userProcessContainer,UserAccount account, GranterWorkRequest request,  EcoSys business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.business=business;
        this.account=account;
        //requestedAmount.setText("500");
        populateboxes();
    }
    
    
    private void populateboxes(){
        requestedAmount.setText(request.getBill());
        PatientName.setText(request.getPatient());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        requestedAmount = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        grantedAmount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        message = new javax.swing.JTextField();
        approveBox = new javax.swing.JCheckBox();
        rejectedBox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        PatientName = new java.awt.Label();
        label2 = new java.awt.Label();

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitJButton.setBackground(new java.awt.Color(255, 255, 255));
        submitJButton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel1.setText("Requested Amount");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        requestedAmount.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        requestedAmount.setEnabled(false);
        requestedAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestedAmountActionPerformed(evt);
            }
        });
        add(requestedAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 170, 30));

        backJButton.setBackground(new java.awt.Color(255, 255, 255));
        backJButton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel2.setText("GRANTER RESULT");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel3.setText("Amount to be Granted");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        grantedAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grantedAmountActionPerformed(evt);
            }
        });
        add(grantedAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 170, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel4.setText("Message");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageActionPerformed(evt);
            }
        });
        add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 170, 30));

        approveBox.setText("Approve");
        approveBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBoxActionPerformed(evt);
            }
        });
        add(approveBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        rejectedBox.setText("Reject");
        rejectedBox.setActionCommand("");
        rejectedBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectedBoxActionPerformed(evt);
            }
        });
        add(rejectedBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, -1, -1));

        PatientName.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        PatientName.setName(""); // NOI18N
        add(PatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 129, -1));

        label2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        label2.setText("Patient Name :");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        GranterWorkAreaJPanel dwjp = (GranterWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        if(message.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Do not enter a empty  message!!");
            return;
            
        }
        else if(message.getText().length()>25)
        {
            JOptionPane.showMessageDialog(null,"DO not exceed 25 characters limit !!");
            return;
            
        }else if(approveBox.isSelected() && rejectedBox.isSelected()){
            JOptionPane.showMessageDialog(null,"please select only 1 check box!!");
            return;
            
        }
        else if(approveBox.isSelected()==false && rejectedBox.isSelected()==false){
            JOptionPane.showMessageDialog(null,"please select  1 check box!!");
            return;
            
        }else {
            
                try{

                    Integer.parseInt(grantedAmount.getText());
                }catch(Exception ex){
                         JOptionPane.showMessageDialog(null,"Enter a valid Amount");
                             return;
                }
                
            request.setGrantingAmount((grantedAmount.getText()));
            
            JOptionPane.showMessageDialog(null,"Completed");     
            
            if(approveBox.isSelected()){
                
                if(Integer.parseInt(grantedAmount.getText())<=0 && Integer.parseInt(grantedAmount.getText())>=Integer.parseInt(request.getBill())){
                            JOptionPane.showMessageDialog(null,"Enter a valid Amount");
                             return;
                }
                
                
            request.setGrantingstatus("Approved");
                this.status="Claim Approved";
            }if(rejectedBox.isSelected()){
                this.status="Claim Rejected";
                request.setGrantingstatus("Rejected");
            }
            
            BillingWorkRequest newrequest = new BillingWorkRequest();
        
            newrequest.setMessage(message.getText());
            newrequest.setSender(account);
            newrequest.setClaimstatus(status); ///add condition
            newrequest.setType("Patient");
            newrequest.setPatient(request.getPatient());
            newrequest.setForwardrequest(status);
            
            int temp=Integer.parseInt(request.getBill());
            
            try{
                
             temp = Integer.parseInt(request.getBill()) - Integer.parseInt(grantedAmount.getText());
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "");
            }
            
            this.amount=String.valueOf(temp);
            newrequest.setBill(String.valueOf(temp));
            

            Organization org = null;
            for (Organization organization : business.getNetworkList().get(0).getEnterpriseDirectory().getEnterpriseList().get(1).getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof OrgBillings) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(newrequest);
                //userAccount.getWorkQueue().getWorkRequestList().add(request);
            }
            
        
             try {
                sendemailto();
            } catch (Exception ex) {
                Logger.getLogger(BillGeneratorWorkAreaJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            JOptionPane.showMessageDialog(null, "Request sent to Govt for funds ");
            
            ///can add email
        }
    }//GEN-LAST:event_submitJButtonActionPerformed

    
     public void sendemailto() throws Exception {
        //MailClass mailclass=new MailClass(txtemail.getText(),"You are registered to Brigham Hospital","Registeration-Brigham");
        // mailclass.sendmail();
        PatientInfoJPanel p = null;
        String text = request.getEmail();
        String name = request.getPatient();
        MailNew m = new MailNew(text, name + " , Your bill has been processed", "Your claim has been " + status + ". The remaing amount is now " + amount);
    }
    
    
    private void requestedAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestedAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestedAmountActionPerformed

    private void grantedAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grantedAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grantedAmountActionPerformed

    private void messageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageActionPerformed

    private void rejectedBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectedBoxActionPerformed
       approveBox.setEnabled(false); 
       grantedAmount.setEnabled(false);
       // TODO add your handling code here:
    }//GEN-LAST:event_rejectedBoxActionPerformed

    private void approveBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBoxActionPerformed
        rejectedBox.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_approveBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       grantedAmount.setEnabled(false);
       approveBox.setEnabled(true);
       rejectedBox.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label PatientName;
    private javax.swing.JCheckBox approveBox;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField grantedAmount;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private java.awt.Label label2;
    private javax.swing.JTextField message;
    private javax.swing.JCheckBox rejectedBox;
    private javax.swing.JTextField requestedAmount;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
